module.exports = {
    CATEGORIES_EN_GB: {
        'breaking' : "<p>Breaking news at <say-as interpret-as='characters'>ABC</say-as></p>><p>Britain has joined the United States in temporarily banning carry-on electronic devices on planes coming from certain airports in Muslim-majority countries in the Middle East and North Africa in response to unspecified security threats.</p><p>The US Department of Homeland Security said passengers traveling from those airports could not bring devices such as tablets, portable DVD players, laptops and cameras into the main cabin that are larger than a mobile phone.</p><p>Instead, such items must be in checked baggage, it said on Tuesday, local time. At this stage, the Australian Government says it has no plans to enact a similar ban.</p>",
        'latest': "<p>Here\'s the latest <say-as interpret-as='characters'>ABC</say-as> news.</p><p>Banks will not be allowed to foreclose on struggling Queensland farmers without first offering them debt mediation under new laws passed in State Parliament. </p><p>Labor and the LNP supported the Farm Business Debt Mediation Bill, which would require financial institutions to offer mediation to farmers who were in arrears before starting enforcement action.</p><p>Queensland Agriculture Minister Bill Byrne said it was an alternative to expensive and drawn-out legal battles.</p>",
        'sports': "<p>Captain Virat Kohli is no longer the most important wicket in India's Test side, at least according to the International Cricket Council's rankings.</p><p>Kohli has slipped below team-mate Cheteshwar Pujara in the latest table released by the ICC. Australia skipper Steve Smith remains the top-ranked batsman in the world with 941 rating points out of a possible 1000.</p><p>Don Bradman (961), Len Hutton (945), Jack Hobbs and Ricky Ponting (942) are the only Test batsmen to have achieved a higher number of rating points than Smith in the history of the sport, according to the ICC's formula.</p>",
    },
    CATEGORIES_EN_US: {
        'breaking' : "<p>Breaking news at <say-as interpret-as='characters'>ABC</say-as></p>><p>Britain has joined the United States in temporarily banning carry-on electronic devices on planes coming from certain airports in Muslim-majority countries in the Middle East and North Africa in response to unspecified security threats.</p><p>The US Department of Homeland Security said passengers traveling from those airports could not bring devices such as tablets, portable DVD players, laptops and cameras into the main cabin that are larger than a mobile phone.</p><p>Instead, such items must be in checked baggage, it said on Tuesday, local time. At this stage, the Australian Government says it has no plans to enact a similar ban.</p>",
        'latest': "<p>Here\'s the latest <say-as interpret-as='characters'>ABC</say-as> news.</p><p>Banks will not be allowed to foreclose on struggling Queensland farmers without first offering them debt mediation under new laws passed in State Parliament. </p><p>Labor and the LNP supported the Farm Business Debt Mediation Bill, which would require financial institutions to offer mediation to farmers who were in arrears before starting enforcement action.</p><p>Queensland Agriculture Minister Bill Byrne said it was an alternative to expensive and drawn-out legal battles.</p>",
        'sports': "<p>Captain Virat Kohli is no longer the most important wicket in India's Test side, at least according to the International Cricket Council's rankings.</p><p>Kohli has slipped below team-mate Cheteshwar Pujara in the latest table released by the ICC. Australia skipper Steve Smith remains the top-ranked batsman in the world with 941 rating points out of a possible 1000.</p><p>Don Bradman (961), Len Hutton (945), Jack Hobbs and Ricky Ponting (942) are the only Test batsmen to have achieved a higher number of rating points than Smith in the history of the sport, according to the ICC's formula.</p>",
    }
};