AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Prototype for ABC news in Alexa
Resources:
  abcalexanews:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: Prototype for ABC news in Alexa
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::190712822094:role/abc_news'
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
